services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  flink:
    build: .
    container_name: flink
    ports:
      - "8081:8081"
    environment:
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=4
    volumes:
      - ./flink-jobs/flink.py:/opt/flink-jobs/flink.py
      - ./jars/flink-connector-kafka-3.0.1-1.18.jar:/opt/flink/lib/flink-connector-kafka-3.0.1-1.18.jar
      - ./jars/kafka-clients-3.5.1.jar:/opt/flink/lib/kafka-clients-3.5.1.jar
      - ./jars/postgresql-42.6.0.jar:/opt/flink/lib/postgresql-42.6.0.jar
      - ./jars/flink-connector-jdbc_2.12-1.14.6.jar:/opt/flink/lib/flink-connector-jdbc_2.12-1.14.6.jar
    command: bash -c "bin/start-cluster.sh && tail -f /dev/null"

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80" # host:container
    depends_on:
      - postgres

volumes:
  postgres_data:
