services:
  # Hive Metastore for Iceberg catalog
  hive-metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore
    environment:
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_NAME: metastore
      DB_USER: hive
      DB_PASS: hive
    ports:
      - "9083:9083"
    depends_on:
      - mysql
    volumes:
      - hive-metastore-data:/opt/hive/data
    networks:
      - spark-network

  # MySQL for Hive Metastore
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spark-network

  spark:
    build: .
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./job.py:/opt/spark-apps/job.py
      - ./imdb_etl.py:/opt/spark-apps/imdb_etl.py
      - ./:/opt/spark-apps
      - warehouse-data:/opt/data/warehouse
      - raw-data:/opt/data/raw
    depends_on:
      - hive-metastore
    networks:
      - spark-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    # MUST BE OFF VPN FOR THIS TO WORK
    extra_hosts:
      - "host.docker.internal:host-gateway"

  spark-worker:
    build: .
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - warehouse-data:/opt/data/warehouse
      - raw-data:/opt/data/raw
    depends_on:
      - spark
    networks:
      - spark-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  hive-metastore-data:
  mysql-data:
  warehouse-data:
  raw-data:

networks:
  spark-network:
    driver: bridge
